In [1]:
#importing the important modules
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import re
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.decomposition import PCA
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
import tensorflow as tf
import keras

Using TensorFlow backend.


In [2]:
#loading all the files in the form of data frames
facebook_economy = pd.read_csv("Facebook_Economy.csv")
facebook_microsoft = pd.read_csv("Facebook_Microsoft.csv")
facebook_obama = pd.read_csv("Facebook_Obama.csv")
facebook_palestine = pd.read_csv("Facebook_Palestine.csv")
googleplus_economy = pd.read_csv("GooglePlus_Economy.csv")
googleplus_microsoft = pd.read_csv("GooglePlus_Microsoft.csv")
googleplus_obama = pd.read_csv("GooglePlus_Obama.csv")
googleplus_palestine = pd.read_csv("GooglePlus_Palestine.csv")
linkedin_economy = pd.read_csv("LinkedIn_Economy.csv")
linkedin_microsoft = pd.read_csv("LinkedIn_Microsoft.csv")
linkedin_obama = pd.read_csv("LinkedIn_Obama.csv")
linkedin_palestine = pd.read_csv("LinkedIn_Palestine.csv")

news_final=pd.read_csv("News_Final.csv")

news_final.describe()
print(news_final.shape)





(93239, 11)


In [3]:
#drop all the rows that have value (-1,-1,-1) for facebook,google+ and linked in
news_final[["Facebook","GooglePlus","LinkedIn"]] = news_final[["Facebook","GooglePlus","LinkedIn"]] .replace(-1, np.NaN)

news_final.dropna(inplace=True)
#to check the number of rows that are left now
print(news_final.shape)

(81406, 11)


In [15]:
#Data cleaning
#removing unnecessary punctuations and tags

def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i, '', input_txt)
    
    return input_txt

""" What vectorize does is it takes a nested sequence of objects or numpy arrays as inputs 
returns a single or tuple of numpy array as output.
"""
news_final['Title'] = np.vectorize(remove_pattern)(news_final['Title'], "@[\\w]*")

#replacing numbers and other special characters with a space in the Title elements
news_final['Title'] = news_final['Title'].str.replace("[^a-zA-Z#]", " ")

news_final['Headline'] = np.vectorize(remove_pattern)(news_final['Headline'], "@[\\w]*")

#replacing numbers and other special characters with a space in the Title elements
news_final['Headline'] = news_final['Headline'].str.replace("[^a-zA-Z#]", " ")

#remove stopwords
stop = stopwords.words('english')
news_final= pd.DataFrame(news_final)
news_final['Title'] = news_final['Title'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))


stop = stopwords.words('english')
news_final= pd.DataFrame(news_final)
news_final['Headline'] = news_final['Headline'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))


news_final

IDLink                                              Title  \
726       311.0  Microsoft offering discount original Band UK p...   
727       252.0  Economy improve though change last months Asso...   
728       227.0  Economy improve though change last months Asso...   
729       307.0    Microsoft scales back free online storage plans   
730       207.0                  IDC predicts emergence DX economy   
731       203.0       Economic Preview Whew U S economy gone rails   
732       299.0  Microsoft OneDrive debacle shows cloud commitm...   
734       294.0                      Economy improve next quarters   
735       209.0  NOW COMES FEDSPEAK Here preview week big marke...   
736       292.0  Get ready ton Fedspeak DJIA SPY SPX QQQ CNY US...   
737       272.0  Pak economy firm level perspective Business Re...   
738       328.0              Microsoft play big part Digital India   
739       232.0         Services pull Scottish economy back growth   
740       587.0         Microsoft risks IT ire Windows update push   
741       201.0  Dollar Goes From Savior Scapegoat Zimbabwe Eco...   
742       476.0  Microsoft readies next major Windows Fall Upda...   
745       240.0  Centre moves aggressively de bottleneck Indian...   
746        15.0              Investing families vital part economy   
747        16.0  CBI downgrades UK growth forecasts global econ...   
748        25.0  Vietnam Growth Masks Weak Local Firms Speed Ec...   
749        28.0                      Economy improve next quarters   
750        33.0     ECB Weidmann German Economy Robust Growth Path   
751        38.0    UK pay rises stay low despite economic recovery   
752        39.0  RPT UPDATE Chinese trade disappoints clouding ...   
753        42.0  Philippines economy thrives young workers stay...   
754        64.0           China brink major milestone consequences   
755        74.0                 Shareholder short termism damaging   
756        75.0  Croatia goes polls facing migrant wave economi...   
757        81.0      Movers shakers honoured Pearls Polish Economy   
758        87.0                         Cartoon Heng China Economy   
...         ...                                                ...   
93113  104755.0  Putin Letter Offers Obama Sanity Amid Escalati...   
93114  104789.0                    Does Sasha Obama Tweet Probably   
93118  104780.0           Obama heads NATO summit inflection point   
93119  104776.0           Obama heads NATO summit inflection point   
93121  104744.0  Bill O Reilly reveals unseen photos Barack Oba...   
93122  104779.0     Obama seeks reassure Canada Mexico Trump trade   
93132  104786.0         Obama heads Europe amid Brexit aftershocks   
93134  104795.0              Obama heads Europe quell Brexit shock   
93149  104796.0  Obama heads Europe amid British referendum aft...   
93151  104802.0               Obama leaves NATO summit visit Spain   
93152  104801.0  Obama heads Europe amid British referendum aft...   
93156  104762.0                                  Obama final fight   
93163  104775.0                   If You Like Obama You Love Trump   
93164  104761.0  President Obama Heads Europe Amid Brexit Refer...   
93169  104790.0  Obama ISIS strategy could hurt Hillary bid Dar...   
93175  104767.0             Celebrating Ramadan occupied Palestine   
93181  104771.0  Palestinian Authority Pays Terrorists Their Fa...   
93182  104770.0  For Blair Iraq war route solving Israel Palestine   
93189  104774.0           Obama heads NATO summit inflection point   
93191  104773.0  Palestine Quartet Two State Solution Sink Poli...   
93192  104777.0  REVEALED AMAZING pics Obama full Muslim dress ...   
93193  104792.0  Putin Called Obama Discuss Syria Ukraine Karabakh   
93210  104787.0  Poland Rushes Vote Unblock Top Court Before Ob...   
93212  104784.0                Why Did Obama Do Well Supreme Court   
93213  104782.0  Ugandan President Repeatedly Refers To Israel ...   
93218  104788.0  De

In [5]:
news_final.dtypes

IDLink               float64
Title                 object
Headline              object
Source                object
Topic                 object
PublishDate           object
SentimentTitle       float64
SentimentHeadline    float64
Facebook             float64
GooglePlus           float64
LinkedIn             float64
dtype: object

In [6]:
#we are creating a list with zipped values of id,title,headline,source,topic and number of shares for Facebook
z=[]
z=list(zip(news_final['IDLink'],news_final['Title'],news_final['Headline'],news_final['Source'],news_final['Topic'],news_final['Facebook']))

#sorting the list in ascending order according to number of shares
z1=sorted(z, key=lambda t: t[5])

#creating a dataframe to store the list elements into the dataframe
labels = ['IDLink','Title', 'Headline','Source', 'Topic', 'SharesOfFacebook']
df_facebook = pd.DataFrame.from_records(z1, columns=labels)

#dividing the shares in categories to improve the accuracy of the algorithm
def label_emotion (row):
   if row['SharesOfFacebook'] >=0 and row['SharesOfFacebook'] <=12500  :
      return 1
   if row['SharesOfFacebook'] > 12500 and row['SharesOfFacebook']<=25000:
      return 2
   if row['SharesOfFacebook'] > 25000 and row['SharesOfFacebook']<=37500:
      return 3
   if row['SharesOfFacebook'] >37500 and row['SharesOfFacebook'] <=50000:
      return 4
df_facebook['category_facebook'] = df_facebook.apply (lambda row: label_emotion (row),axis=1)

df_facebook




IDLink                                              Title  \
0         311.0  Microsoft offering discount original Band UK p...   
1         252.0  Economy improve though change last months Asso...   
2         227.0  Economy improve though change last months Asso...   
3         307.0    Microsoft scales back free online storage plans   
4         272.0  Pak economy firm level perspective Business Re...   
5         232.0         Services pull Scottish economy back growth   
6         240.0  Centre moves aggressively de bottleneck Indian...   
7         127.0  First impressions Microsoft Surface Pro coming...   
8         149.0   Latest acquisition marks Microsoft mobility move   
9         563.0         COMESA Signs Up Microsoft Cloud Protection   
10        564.0  OPERATING SYSTEMS Microsoft Starts Pushing Upg...   
11        584.0                                      False Economy   
12        390.0  Microsoft Summit Six technologies accelerate d...   
13        241.0  Turkish economy may grow percent finance minister   
14        502.0  KSA plans center modeled Korea creative econom...   
15        236.0         UK economy grow robust pace forecasts OECD   
16        208.0                             Get ready ton Fedspeak   
17         83.0  ECONOMIC WEEK AHEAD Data may answer crunch que...   
18        302.0  MTM Technologies Inc Becomes Microsoft Authori...   
19        204.0             Go green save world world economy OECD   
20         40.0         Weidmann German economy robust growth path   
21        243.0  Hackers costing Northern Ireland economy nearl...   
22        280.0  Global Economy Holding Pattern But No Hard Lan...   
23        451.0  World NewsOECD Migrant flow boost European eco...   
24         53.0  Bizarre Ben Carson Quotes On The Economy Like ...   
25         56.0                   Lewis blames economy profit drop   
26        138.0     Microsoft seeks impart pure Windows experience   
27        301.0  Microsoft reveals first batch backward compati...   
28         34.0       Can Climate Change Be Addressed Weak Economy   
29        568.0  MTM Technologies Inc Becomes Microsoft Authori...   
...         ...                                                ...   
81376   79096.0  This photo Obama little visitor Black History ...   
81377   70985.0    Barack Obama Guns Are Our Shared Responsibility   
81378  101578.0         Israel cuts water supply West Bank Ramadan   
81379   65185.0     The facts shoot holes Obama claim US host mass   
81380   70621.0                      Obama lied buying guns online   
81381   62272.0  Hours After Obama Taunts GOP With Widows Femal...   
81382   63480.0  Sen Sessions Reveals Refugee Jihadis To Shrink...   
81383   98809.0         Pete Souza photographing real Barack Obama   
81384  101650.0  WATCH th Grader Nails Impersonations Of Trump ...   
81385   62536.0  US Pilots Confirm Obama Admin Blocks Percent I...   
81386   50703.0  Microsoft Nadella Meet India CEOs Tech Leaders...   
81387   67548.0  Old Dixie changed President Barack Obama Highw...   
81388   31272.0     Microsoft allow Xbox gamers play PS PC players   
81389   74359.0  Obama bans solitary confinement juveniles fede...   
81390   90631.0  Saudi Arabia Warns Economic Fallout Congress P...   
81391   94081.0             Obama Frees USS Cole Bombing Terrorist   
81392   90713.0            Why Obama crack corporate mergers right   
81393   23117.0  Under Sanders income jobs would soar economist...   
81394   67141.0  President Obama Singing Hotline Bling Is The B...   
81395   65424.0  Obama Hires Former Hamas Terrorist For His ISI...   
81396   23208.0                        Microsoft Cortana take crap   
81397   29108.0  GZ Roundtable Is Microsoft effort bring Xbox O...   
81398   35873.0  Microsoft teen girl AI turns Hitler loving sex...   
81399   67508.0  Paul Ryan Betrays America Trillion Plus Page O...   
81400   62638.0                        How inner Obama fights ISIS   
81401   12561.0  Fo

In [7]:
#we are creating a list with zipped values of id,title,headline,source,topic and number of shares for GooglePlus
z=[]
z=list(zip(news_final['IDLink'],news_final['Title'],news_final['Headline'],news_final['Source'],news_final['Topic'],news_final['GooglePlus']))

#sorting the list in ascending order according to number of shares
z1=sorted(z, key=lambda t: t[5])

#creating a dataframe to store the list elements into the dataframe
labels = ['IDLink','Title', 'Headline','Source', 'Topic', 'SharesOfGooglePlus']
df_googlePlus = pd.DataFrame.from_records(z1, columns=labels)

#dividing the shares in categories to improve the accuracy of the algorithm
def label_emotion (row):
   if row['SharesOfGooglePlus'] >=0 and row['SharesOfGooglePlus'] <=65  :
      return 1
   if row['SharesOfGooglePlus'] > 65 and row['SharesOfGooglePlus']<=130:
      return 2
   if row['SharesOfGooglePlus'] > 130 and row['SharesOfGooglePlus']<=195:
      return 3
   if row['SharesOfGooglePlus'] >195 and row['SharesOfGooglePlus'] <=260:
      return 4
   if row['SharesOfGooglePlus'] >260 and row['SharesOfGooglePlus'] <=325:
      return 5
   if row['SharesOfGooglePlus'] >325 and row['SharesOfGooglePlus'] <=390:
      return 6
   if row['SharesOfGooglePlus'] >390 and row['SharesOfGooglePlus'] <=455:
      return 7
   if row['SharesOfGooglePlus'] >455 and row['SharesOfGooglePlus'] <=520:
      return 8
   if row['SharesOfGooglePlus'] >520 and row['SharesOfGooglePlus'] <=585:
      return 9
   if row['SharesOfGooglePlus'] >585 and row['SharesOfGooglePlus'] <=650:
      return 10
   if row['SharesOfGooglePlus'] >=650 and row['SharesOfGooglePlus'] <=715  :
      return 11
   if row['SharesOfGooglePlus'] > 715 and row['SharesOfGooglePlus']<=780:
      return 12
   if row['SharesOfGooglePlus'] > 780 and row['SharesOfGooglePlus']<=845:
      return 13
   if row['SharesOfGooglePlus'] >845 and row['SharesOfGooglePlus'] <=910:
      return 14
   if row['SharesOfGooglePlus'] >910 and row['SharesOfGooglePlus'] <=975:
      return 15
   if row['SharesOfGooglePlus'] >975 and row['SharesOfGooglePlus'] <=1040:
      return 16
   if row['SharesOfGooglePlus'] >1040 and row['SharesOfGooglePlus'] <=1105:
      return 17
   if row['SharesOfGooglePlus'] >1105 and row['SharesOfGooglePlus'] <=1170:
      return 18
   if row['SharesOfGooglePlus'] >1170 and row['SharesOfGooglePlus'] <=1235:
      return 19
   if row['SharesOfGooglePlus'] >1235 and row['SharesOfGooglePlus'] <=1300:
      return 20
df_googlePlus['category_GooglePlus'] = df_googlePlus.apply (lambda row: label_emotion (row),axis=1)

df_googlePlus

#on dividing into more number of categories,it gives better accuracy 99.6(ten categories) 99.8(twenty categories)

IDLink                                              Title  \
0        311.0  Microsoft offering discount original Band UK p...   
1        252.0  Economy improve though change last months Asso...   
2        227.0  Economy improve though change last months Asso...   
3        307.0    Microsoft scales back free online storage plans   
4        207.0                  IDC predicts emergence DX economy   
5        203.0       Economic Preview Whew U S economy gone rails   
6        299.0  Microsoft OneDrive debacle shows cloud commitm...   
7        294.0                      Economy improve next quarters   
8        209.0  NOW COMES FEDSPEAK Here preview week big marke...   
9        272.0  Pak economy firm level perspective Business Re...   
10       232.0         Services pull Scottish economy back growth   
11       587.0         Microsoft risks IT ire Windows update push   
12       201.0  Dollar Goes From Savior Scapegoat Zimbabwe Eco...   
13       240.0  Centre moves aggressively de bottleneck Indian...   
14        28.0                      Economy improve next quarters   
15        33.0     ECB Weidmann German Economy Robust Growth Path   
16        39.0  RPT UPDATE Chinese trade disappoints clouding ...   
17        75.0  Croatia goes polls facing migrant wave economi...   
18       127.0  First impressions Microsoft Surface Pro coming...   
19       132.0        Microsoft IRS spar long running probe taxes   
20       147.0  Microsoft Adds Java Debugging And Language Sup...   
21       149.0   Latest acquisition marks Microsoft mobility move   
22       449.0                         Whew US economy gone rails   
23       556.0    RPT GLOBAL ECONOMY WEEKAHEAD US pessimism burns   
24       562.0  Now Microsoft adding Mobile Data Lab catalog M...   
25       563.0         COMESA Signs Up Microsoft Cloud Protection   
26       564.0  OPERATING SYSTEMS Microsoft Starts Pushing Upg...   
27       390.0  Microsoft Summit Six technologies accelerate d...   
28       241.0  Turkish economy may grow percent finance minister   
29       502.0  KSA plans center modeled Korea creative econom...   
...        ...                                                ...   
81376  29734.0           Revealed year economic betrayal dragging   
81377  19593.0  Microsoft Open Sources Its Artificial Brain On...   
81378  78362.0      Palestinian identity created response Zionism   
81379  19585.0  Microsoft Open Sources Its Artificial Brain On...   
81380  94489.0                Obama sending extra US troops Syria   
81381  79184.0      Roger Waters Pink Floyd star fellow musicians   
81382   8840.0  Microsoft Will Let You Keep Your Free GB Of On...   
81383  30172.0  Microsoft release custom Debian Linux Repeat c...   
81384  63460.0  Outrage military vehicles equipment taken offi...   
81385  14383.0      Microsoft pulling plug Internet Explorer next   
81386  31272.0     Microsoft allow Xbox gamers play PS PC players   
81387  30848.0  Microsoft crafted Debian Linux switch OS Repea...   
81388  67508.0  Paul Ryan Betrays America Trillion Plus Page O...   
81389  79613.0  Obama Signs Executive Order Relocating Congres...   
81390  38474.0              Microsoft bringing Bash shell Windows   
81391  23326.0      Tests Reveal Windows Spying Is Out Of Control   
81392  68177.0                          Paul aims rein Obama guns   
81393  74359.0  Obama bans solitary confinement juveniles fede...   
81394   7555.0  The Isis papers leaked documents show Isis bui...   
81395  12279.0  Recently Bought Windows Computer Microsoft Pro...   
81396  17259.0         Microsoft says new processors work Windows   
81397  66473.0  Police Chief Revolution Coming Obama Tries Disarm   
81398  75688.0   Michele Bachmann warns Obama take United Nations   
81399  12561.0  For Wealthiest Private Tax System That Saves T...   
81400  38319.0   Microsoft Canonical partner bring Ubuntu Windows   
81401   2070.0  Intervention PM G working session Inclusive Gr...   
81402 

In [8]:
#we are creating a list with zipped values of id,title,headline,source,topic and number of shares for LinkedIn
z=[]
z=list(zip(news_final['IDLink'],news_final['Title'],news_final['Headline'],news_final['Source'],news_final['Topic'],news_final['LinkedIn']))

#sorting the list in ascending order according to number of shares
z1=sorted(z, key=lambda t: t[5])

#creating a dataframe to store the list elements into the dataframe
labels = ['IDLink','Title', 'Headline','Source', 'Topic', 'SharesOfLinkedIn']
df_linkedIn = pd.DataFrame.from_records(z1, columns=labels)

#dividing the shares in categories to improve the accuracy of the algorithm
def label_emotion (row):
   if row['SharesOfLinkedIn'] >=0 and row['SharesOfLinkedIn'] <=1600  :
      return 1
   if row['SharesOfLinkedIn'] > 1600 and row['SharesOfLinkedIn']<=3200:
      return 2
   if row['SharesOfLinkedIn'] > 3200 and row['SharesOfLinkedIn']<=4800:
      return 3
   if row['SharesOfLinkedIn'] >4800 and row['SharesOfLinkedIn'] <=6400:
      return 4
df_linkedIn['category_LinkedIn'] = df_linkedIn.apply (lambda row: label_emotion (row),axis=1)

df_linkedIn


IDLink                                              Title  \
0         311.0  Microsoft offering discount original Band UK p...   
1         252.0  Economy improve though change last months Asso...   
2         227.0  Economy improve though change last months Asso...   
3         307.0    Microsoft scales back free online storage plans   
4         207.0                  IDC predicts emergence DX economy   
5         203.0       Economic Preview Whew U S economy gone rails   
6         209.0  NOW COMES FEDSPEAK Here preview week big marke...   
7         272.0  Pak economy firm level perspective Business Re...   
8         232.0         Services pull Scottish economy back growth   
9         587.0         Microsoft risks IT ire Windows update push   
10        240.0  Centre moves aggressively de bottleneck Indian...   
11         75.0  Croatia goes polls facing migrant wave economi...   
12         81.0      Movers shakers honoured Pearls Polish Economy   
13        127.0  First impressions Microsoft Surface Pro coming...   
14        149.0   Latest acquisition marks Microsoft mobility move   
15        464.0  LOOK Aaron Rodgers gets upset slams tablet sid...   
16        521.0  NDA defeat Bihar setback economy says Arun Jai...   
17        556.0    RPT GLOBAL ECONOMY WEEKAHEAD US pessimism burns   
18        563.0         COMESA Signs Up Microsoft Cloud Protection   
19        564.0  OPERATING SYSTEMS Microsoft Starts Pushing Upg...   
20        584.0                                      False Economy   
21        390.0  Microsoft Summit Six technologies accelerate d...   
22        241.0  Turkish economy may grow percent finance minister   
23        502.0  KSA plans center modeled Korea creative econom...   
24        100.0                             Rocket fuel US economy   
25        236.0         UK economy grow robust pace forecasts OECD   
26        202.0  Tale two Californias Coastal voters upbeat eco...   
27        208.0                             Get ready ton Fedspeak   
28         83.0  ECONOMIC WEEK AHEAD Data may answer crunch que...   
29        128.0  Apple iPad Pro vs Microsoft Surface Pro A Comp...   
...         ...                                                ...   
81376   57259.0         Salesforce com Lost LinkedIn Bid Microsoft   
81377   21784.0  Microsoft Is Acquiring London AI Driven SwiftK...   
81378   72807.0   President Obama Proposes Wage Insurance Expanded   
81379   17806.0          These Are World Most Innovative Economies   
81380    5493.0        Founders Microsoft Facebook LinkedIn Amazon   
81381  104089.0          Obama After Dark The Precious Hours Alone   
81382   57740.0           Donald Trump Would Wreck The U S Economy   
81383   36303.0  Microsoft apologizes offensive hurtful tweets ...   
81384   12765.0                                        Brazil fall   
81385   30490.0  How Microsoft Research Project Captured Hearts...   
81386   22281.0   If There Is Recession This Is How It Will Happen   
81387   13396.0        Over Female Jobless Even Others Return Work   
81388   27515.0            Microsoft Word hacks know lived without   
81389   74997.0  Obama Moves Expand Rules Aimed Closing Gender ...   
81390    7542.0  Future bright Manitoba economy says Conference...   
81391   43985.0  The Trillion Project Get Saudi Arabia Economy ...   
81392   38474.0              Microsoft bringing Bash shell Windows   
81393   54836.0  Economy Jobs Threatened Machines A Once Stupid...   
81394   28349.0  Our Economy Is Obsessed Efficiency Terrible Ev...   
81395   52118.0  The World Largest Tech Companies Apple Bests S...   
81396   24651.0                  What Stake Economy Low Oil Prices   
81397   21154.0  Microsoft Plumbs Ocean Depths Test Underwater ...   
81398   35982.0        The Things It Takes Succeed Digital Economy   
81399   52101.0  Facebook Microsoft Are Laying Giant Cable Acro...   
81400   38485.0        Microsoft adding Linux command line Windows   
81401   30049.0  Th

In [9]:
"""Keras provides the one_hot() function that creates a hash of each word as an efficient integer encoding.
We will estimate the vocabulary size of 50, 
which is much larger than needed to reduce the probability of collisions from the hash function.
"""
from keras.preprocessing.text import one_hot#import has not been moved from here for better understandability of the code
# integer encode the documents
vocab_size = 100
encoded_docs = [one_hot(d, vocab_size) for d in df_facebook['Title']]


"""The sequences have different lengths and Keras prefers inputs to be vectorized and all inputs to have the same length. 
We will pad all input sequences to have the length of 4.
Again, we can do this with a built in Keras function, in this case the pad_sequences() function.
pad documents to a max length of 4 words
"""
from keras.preprocessing.sequence import pad_sequences
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')



"""We are now ready to define our Embedding layer as part of our neural network model.
The Embedding has a vocabulary of 50 and an input length of 4. We will choose a small embedding space of 8 dimensions.
The model is a simple binary classification model. 
Importantly, the output from the Embedding layer will be 4 vectors of 8 dimensions each, one for each word. 
We flatten this to a one 32-element vector to pass on to the Dense output layer.
define the model
"""
from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense, Dropout, Flatten
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['acc'])#loss='binary_crossentropy'


#Finally, we can fit and evaluate the classification model.
# fit the model
model.fit(padded_docs, df_facebook['category_facebook'], epochs=20, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, df_facebook['category_facebook'], verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 99.964376


In [10]:
"""Keras provides the one_hot() function that creates a hash of each word as an efficient integer encoding.
We will estimate the vocabulary size of 50, 
which is much larger than needed to reduce the probability of collisions from the hash function.
"""
from keras.preprocessing.text import one_hot#import has not been moved from here for better understandability of the code
# integer encode the documents
vocab_size = 100
encoded_docs = [one_hot(d, vocab_size) for d in df_googlePlus['Title']]


"""The sequences have different lengths and Keras prefers inputs to be vectorized and all inputs to have the same length. 
We will pad all input sequences to have the length of 4.
Again, we can do this with a built in Keras function, in this case the pad_sequences() function.
 pad documents to a max length of 4 words
 """
from keras.preprocessing.sequence import pad_sequences
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')


"""We are now ready to define our Embedding layer as part of our neural network model.
The Embedding has a vocabulary of 50 and an input length of 4. We will choose a small embedding space of 8 dimensions.
The model is a simple binary classification model. 
Importantly, the output from the Embedding layer will be 4 vectors of 8 dimensions each, one for each word. 
We flatten this to a one 32-element vector to pass on to the Dense output layer.
define the model
"""
from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense, Dropout, Flatten
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['acc'])#loss='binary_crossentropy'


#Finally, we can fit and evaluate the classification model.
# fit the model
model.fit(padded_docs, df_googlePlus['category_GooglePlus'], epochs=20, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, df_googlePlus['category_GooglePlus'], verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 98.858806


In [11]:
"""Keras provides the one_hot() function that creates a hash of each word as an efficient integer encoding.
We will estimate the vocabulary size of 50, 
which is much larger than needed to reduce the probability of collisions from the hash function.
"""

from keras.preprocessing.text import one_hot#import has not been moved from here for better understandability of the code
# integer encode the documents
vocab_size = 100
encoded_docs = [one_hot(d, vocab_size) for d in df_linkedIn['Title']]


"""The sequences have different lengths and Keras prefers inputs to be vectorized and all inputs to have the same length. 
We will pad all input sequences to have the length of 4.
Again, we can do this with a built in Keras function, in this case the pad_sequences() function.
pad documents to a max length of 4 words
"""
from keras.preprocessing.sequence import pad_sequences
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')


"""We are now ready to define our Embedding layer as part of our neural network model.
The Embedding has a vocabulary of 50 and an input length of 4. We will choose a small embedding space of 8 dimensions.
The model is a simple binary classification model. 
Importantly, the output from the Embedding layer will be 4 vectors of 8 dimensions each, one for each word. 
We flatten this to a one 32-element vector to pass on to the Dense output layer.
define the model
"""
from keras.models import Sequential
from keras.layers import Embedding
from keras.layers import Dense, Dropout, Flatten
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['acc'])#loss='binary_crossentropy'

#Finally, we can fit and evaluate the classification model.
# fit the model
model.fit(padded_docs, df_linkedIn['category_LinkedIn'], epochs=20, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, df_linkedIn['category_LinkedIn'], verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 99.964376


In [12]:
# create the transform
vectorizer = HashingVectorizer(n_features=20)
# encode document
vector = vectorizer.transform(df_facebook['Title'])
vec=vector.toarray()

#Split the data into training and test sets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X = vec
y = df_facebook.iloc[:,6]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)


#Fit logistic regression to the training set
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)


#Predicting the test set results and creating confusion matrix
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))


"""Compute precision, recall, F-measure and support
The precision is the ratio tp / (tp + fp) where tp is the number of true positives and fp the number of false positives.
The precision is intuitively the ability of the classifier to not label a sample as positive if it is negative.
The recall is the ratio tp / (tp + fn) where tp is the number of true positives and fn the number of false negatives. 
The recall is intuitively the ability of the classifier to find all the positive samples.
The F-beta score can be interpreted as a weighted harmonic mean of the precision and recall, where an F-beta score reaches its best value at 1 and worst score at 0.
The F-beta score weights the recall more than the precision by a factor of beta. beta = 1.0 means recall and precision are equally important.
The support is the number of occurrences of each class in y_test.
"""
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[20343     0     0]
 [    8     0     0]
 [    1     0     0]]
Accuracy of logistic regression classifier on test set: 1.00
             precision    recall  f1-score   support

          1       1.00      1.00      1.00     20343
          2       0.00      0.00      0.00         8
          3       0.00      0.00      0.00         1

avg / total       1.00      1.00      1.00     20352



C:\Users\Nikita\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [13]:
# create the transform
vectorizer = HashingVectorizer(n_features=20)
# encode document
vector = vectorizer.transform(df_googlePlus['Title'])
vec=vector.toarray()

#Split the data into training and test sets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X = vec
y = df_googlePlus.iloc[:,6]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

#Fit logistic regression to the training set
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)


#Predicting the test set results and creating confusion matrix
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))


"""Compute precision, recall, F-measure and support
The precision is the ratio tp / (tp + fp) where tp is the number of true positives and fp the number of false positives.
The precision is intuitively the ability of the classifier to not label a sample as positive if it is negative.
The recall is the ratio tp / (tp + fn) where tp is the number of true positives and fn the number of false negatives. 
The recall is intuitively the ability of the classifier to find all the positive samples.
The F-beta score can be interpreted as a weighted harmonic mean of the precision and recall, where an F-beta score reaches its best value at 1 and worst score at 0.
The F-beta score weights the recall more than the precision by a factor of beta. beta = 1.0 means recall and precision are equally important.
The support is the number of occurrences of each class in y_test.
"""
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[20121     0     0     0     0     0     0     0     0     0     0]
 [  155     0     0     0     0     0     0     0     0     0     0]
 [   43     0     0     0     0     0     0     0     0     0     0]
 [   16     0     0     0     0     0     0     0     0     0     0]
 [    6     0     0     0     0     0     0     0     0     0     0]
 [    3     0     0     0     0     0     0     0     0     0     0]
 [    4     0     0     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0     0     0]
 [    1     0     0     0     0     0     0     0     0     0     0]]
Accuracy of logistic regression classifier on test set: 0.99
             precision    recall  f1-score   support

          1       0.99      1.00      0.99     20121
          2       0.00      0.00      0.00       155
          3       0

C:\Users\Nikita\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [14]:
# create the transform
vectorizer = HashingVectorizer(n_features=20)
# encode document
vector = vectorizer.transform(df_linkedIn['Title'])
vec=vector.toarray()

#Split the data into training and test sets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X = vec
y = df_linkedIn.iloc[:,6]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

#Fit logistic regression to the training set
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

#Predicting the test set results and creating confusion matrix
y_pred = classifier.predict(X_test)


from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

"""Compute precision, recall, F-measure and support
The precision is the ratio tp / (tp + fp) where tp is the number of true positives and fp the number of false positives.
The precision is intuitively the ability of the classifier to not label a sample as positive if it is negative.
The recall is the ratio tp / (tp + fn) where tp is the number of true positives and fn the number of false negatives. 
The recall is intuitively the ability of the classifier to find all the positive samples.
The F-beta score can be interpreted as a weighted harmonic mean of the precision and recall, where an F-beta score reaches its best value at 1 and worst score at 0.
The F-beta score weights the recall more than the precision by a factor of beta. beta = 1.0 means recall and precision are equally important.
The support is the number of occurrences of each class in y_test.
"""
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[20343     0     0]
 [    8     0     0]
 [    1     0     0]]
Accuracy of logistic regression classifier on test set: 1.00
             precision    recall  f1-score   support

          1       1.00      1.00      1.00     20343
          2       0.00      0.00      0.00         8
          3       0.00      0.00      0.00         1

avg / total       1.00      1.00      1.00     20352



C:\Users\Nikita\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
import pandas as pd
import numpy as np
import scipy.stats as stats
from scipy.stats import chi2_contingency

class ChiSquare:
   def __init__(self, dataframe):
       self.df = dataframe
       self.p = None #P-Value
       self.chi2 = None #Chi Test Statistic
       self.dof = None

       self.dfObserved = None
       self.dfExpected = None

   def _print_chisquare_result(self, colX, alpha):
       result = ""
       if self.p<alpha:
           result="{0} is IMPORTANT for Prediction".format(colX)
       else:
           result="{0} is NOT an important predictor. (Discard {0} from model)".format(colX)

       print(result)

   def TestIndependence(self,colX,colY, alpha=0.05):
       X = self.df[colX].astype(str)
       Y = self.df[colY].astype(str)

       self.dfObserved = pd.crosstab(Y,X)
       chi2, p, dof, expected = stats.chi2_contingency(self.dfObserved.values)
       self.p = p
       self.chi2 = chi2
       self.dof = dof

       self.dfExpected = pd.DataFrame(expected, columns=self.dfObserved.columns, index = self.dfObserved.index)

       self._print_chisquare_result(colX,alpha)

df = pd.pandas.read_csv("news_final.csv")

#Initialize ChiSquare Class
cT = ChiSquare(df)

#Feature Selection
testColumns = ['Title','Headline','Source']
for var in testColumns:
    cT.TestIndependence(colX=var,colY="Facebook")

Title is IMPORTANT for Prediction
Headline is IMPORTANT for Prediction
Source is NOT an important predictor. (Discard Source from model)
